### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zyp0209** [404cn/bitwarden_go#2]
![image](https://user-images.githubusercontent.com/5607709/77815286-80980900-70f4-11ea-9c6a-da641af58539.png)

System: CentOS 7 x64
Go version: go version go1.14 linux/amd64

**Comment by zyp0209** [comment]
![image](https://user-images.githubusercontent.com/5607709/77815662-aecb1800-70f7-11ea-9a90-b54213ff1a80.png)

**Comment by 404cn** [comment]
Sorry. The project is not done yet. I will rebase dev to master and write the doc when I finish it. 
It might take about a month because I do not have much time on it at now. 

If you want self-hosted Bitwarden server. I recommend bitwarden_rs. 

Thank you for your issue and I will keep it open.
